apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opnform.fullname" . }}-{{ .Values.api.name | default "api" }}
  labels:
    {{- include "opnform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- with .Values.api.podLabels }}
      {{- toYaml . | nindent 6}}
      {{- end }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opnform.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      {{- with .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "opnform.fullname" . }}-{{- default "api" .Values.api.name }}
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.api.image.repository }}{{- if .Values.api.image.tag }}:{{ .Values.api.image.tag }}{{- end}}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- with .Values.api.ports }}
          ports: 
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- with .Values.api.secret.env }}
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: JWT_SECRET
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: APP_KEY
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "opnform.fullname" . }}- {{- .Values.api.config.name | default "api-config"}}
            {{- with .Values.api.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

