apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "opnform.fullname" . }}- {{- .Values.client.config.name | default "client-config"}}
data:
    NUXT_PRIVATE_API_BASE: "http://{{ include "opnform.fullname" . }}- {{- .Values.nginx.service.name | default "nginx-service"}}/api"
    {{- with .Values.client.config.data }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
